### PR TITLE
I sent you an email, but i fuigured this would be better

### PR DESCRIPTION
**Pull request by daherr**
So I hope you received and read my email, so this is where I'm at with the code right now, again I'm sorry and that this was my own fault and stupidity so I would be very grateful if you would try to help me fix this problem so I can hopefully turn the program in for Sunday.

### CODE REVIEW

**Comment by daherr** [comment]
Ok so I've read through your comments and there's one thing I don't understand and it's the one thing that's holding me up. I'm confused about how to A. make the user's input into a contact object, and B. how to add that said contact object to the array. I remember talking about it in class, and again I forgot to press sync after I was done, so it messed me up totally. I've been researching online but I haven't found any help because most of what I'm reading is saying to use an arrayList but I don't ever remember talking about those, so I don't want to use it, other than that I should be ok.

**Comment by jwoytek** [comment]
I actually explained how to do that in my comments. The A and B you ask
about are ONE operation, not separate things. You index into the array and
call methods, just like we did in class.

arrayVar[indexVar].doSomething(argument);

The only difference between what you did in the Contact test program and
this is that instead of using a single variable of type Contact and calling
methods like setLastName("foo") on it is that you're calling those methods
on an array reference of type Contact, like:

contacts[indexVar].setLastName(inputFromKeyboard);

Jonathan

On Sunday, December 13, 2015, daherr <notifications@github.com> wrote:

> Ok so I've read through your comments and there's one thing I don't
> understand and it's the one thing that's holding me up. I'm confused about
> how to A. make the user's input into a contact object, and B. how to add
> that said contact object to the array. I remember talking about it in
> class, and again I forgot to press sync after I was done, so it messed me
> up totally. I've been researching online but I haven't found any help
> because most of what I'm reading is saying to use an arrayList but I don't
> ever remember talking abo those, so I don't want to use it, other than that
> I should be ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SJHS-CS0501/ContactWriterReader/pull/4#issuecomment-164294079>
> .
>


-- 
Sent from my Commodore64

**Comment by daherr** [comment]
I'm close to finishing the program, however, I'm getting a weird error that isn't letting me close my file, so I can't run it to see if it actually woks

**Comment by daherr** [comment]
It's line 131 to be specific

**Comment by daherr** [comment]
The program doesn't work, but I've spent so much time on this over the past week, and I still can't even begin to wrap my head around these complex arrays. I've spent over three hours tonight just on that section and I still can't figure it out. If I could talk to you tomorrow and have it be turned in tomorrow,  would be very grateful, but I completely understand if you do not. No matter what I need you to walk me through this, and I've looked and like usual I can't find anything close online. This is beginning to get in my head, and it's bothering me, I thought I understood, but I didn't even come close and I need to get to bed. Like I said I'll talk to you tomorrow.

David

**Comment by jwoytek** [comment]
Ok.

On Wednesday, December 16, 2015, daherr <notifications@github.com> wrote:

> The program doesn't work, but I've spent so much time on this over the
> past week, and I still can't even begin to wrap my head around these
> complex arrays. I've spent over three hours tonight just on that section
> and I still can't figure it out. If I could talk to you tomorrow and have
> it be turned in tomorrow, would be very grateful, but I completely
> understand if you do not. No matter what I need you to walk me through
> this, and I've looked and like usual I can't find anything close online.
> This is beginning to get in my head, and it's bothering me, I thought I
> understood, but I didn't even come close and I need to get to bed. Like I
> said I'll talk to you tomorrow.
>
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SJHS-CS0501/ContactWriterReader/pull/4#issuecomment-165333869>
> .
>


-- 
Sent from my Commodore64

**Comment by jwoytek** [comment]
:+1:

**Pull request closed without merging**
